# Generated by Django 4.2.8 on 2023-12-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thundercar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('dni', models.IntegerField(max_length=8)),
                ('fecNac', models.DateField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
