# Generated by Django 4.2.8 on 2023-12-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_thundercar_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='thundercar',
            new_name='Project',
        ),
    ]
