# Generated by Django 4.2.8 on 2023-12-13 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_rename_thundercar_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='contacto',
        ),
    ]
