# Generated by Django 4.2.8 on 2023-12-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0005_solenoide_delete_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solenoide',
            name='adjuntar',
            field=models.FileField(upload_to=''),
        ),
    ]
